### ISSUE TITLE
Sitefinity 12 support

### ISSUE THREAD

**Issue by cheesesteakjimmy** [sitefinitysteve/RandomSiteControlsMVC#7]
Does this library work against Sitefinity 12? Can we get it updated to be supported?

**Comment by sitefinitysteve** [comment]
Totally does :D

Just assembly bind it up https://www.sitefinitysteve.com/blog/code/2012/03/25/avoid-version-errors-with-assembly-binding

I will be updating it "officially" to the latest 12.1 internal shortly though anyway

You should be on 12.1 just based on the latest security briefing.

I'm gonna close it because it'll work with the bindings k
